### ISSUE TITLE
Cumulative K/O locus tab - add dropdown box for selecting metadata variable to group by

### ISSUE THREAD

**Issue by kelwyres** [kelwyres/Kleborate_viz#21]
Need to check for column names in the metadata file to populate the drop down list and edit the calls to prop.table in cumulative_ko_locus.R to use the selected variable instead of 'Region' - rest of code should then work.

Ideally also edit colours to a nicer palette - need to figure out how to do this when don't know the total number of groups - see also the 'Trends by sample' tab.

**Comment by scwatts** [comment]
User input has been added but colours still need attention. One solution for generating colours for varying number of groups is to define a colour palette generator. For example, the colour palette for 'Other' species in the genotype by ST colours is defined as:
https://github.com/kelwyres/Kleborate-viz/blob/2039bfc34b21bfe9141d0256824539bc0104f198/global.R#L80-L97

This is used to generate n colours, one for each non Kp/KoSC species:
https://github.com/kelwyres/Kleborate-viz/blob/2039bfc34b21bfe9141d0256824539bc0104f198/server.R#L18-L24

If you can provide a set of colours to use for the groups, I'll implement the above for the cumulative ko prevalence plots

**Comment by kelwyres** [comment]
OK great, can we try this 
`v.misc_colour_palette <- colorRampPalette( 
   c( 
     "#E67E78", 
     "#EF9D45", 
     "#E9DD50", 
     "#79BEA8", 
     "#3F57A7", 
     "#885F9A", 
     "#757C82",
   ) 
 ) `

If we define in global - can use in both the cumulative K/O locus plot as well as the sample trends plot.
