### ISSUE TITLE
fix the summary table

### ISSUE THREAD

**Issue by kelwyres** [kelwyres/Kleborate_viz#4]
remove V1/V2 and add any other useful rows

**Comment by katholt** [comment]
I have got rid of the column headings and replaced this with a title "Data Summary"
This is now positioned in the side bar which is visible at all times.
I have also added labels to the species toggles (also in this sidebar, positioned under the summary table) to show how many of each KP species complex (or other species) are present... so this info is presented both as part of the summary, and serves as the check boxes to choose which species to display in plots.
