### ISSUE TITLE
check for all data columns and give sensible errors

### ISSUE THREAD

**Issue by kelwyres** [kelwyres/Kleborate_viz#6]
e.g if species columns K or O locus cols or resistance gene cols are absent - give a message to rerun Kleborate using --all option.

**Comment by scwatts** [comment]
Input validation by presence of specific columns done in https://github.com/kelwyres/Kleborate-viz/commit/f221ab710f7004816c15ed3d31b0bb6d33c1d8db. Error messages generated depending on validation failure but these are general and you may like to change the wording to be more specific
