### ISSUE TITLE
add download PDF to all plots

### ISSUE THREAD

**Issue by kelwyres** [kelwyres/Kleborate_viz#8]

**Comment by katholt** [comment]
I have added this to the res/vir score summary plots on the landing tab.

I have also added a file showing an example of how to add this functionality for new plots (example_code_to_make_PDF_plots.r)... basically you need to move the plot construction functions (e.g. ggplot call) into a reactive function; then you can call this function within your renderPlot call (in the app) AND also within a PDF call. You also need to add a download button to the layout function, and create an associated downloadHandler that makes a PDF file and calls the reactive plotting function.
